version: 2

models:
  - name: fct_orders
    description: "{{ doc('fct_orders') }}"
    columns:
      - name: order_id
        tests: [not_null, unique]
      - name: customer_id
        tests:
          - relationships:
              to: ref('dim_customers')
              field: customer_id
      - name: revenue
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0

  - name: dim_customers
    description: "{{ doc('dim_customers') }}"
    columns:
      - name: customer_id
        tests: [not_null, unique]

  - name: dim_products
    description: "{{ doc('dim_products') }}"
    columns:
      - name: product_id
        tests: [not_null, unique]

  - name: daily_revenue
    description: "{{ doc('daily_revenue') }}"
    columns:
      - name: order_date
        tests: [not_null, unique]

  - name: aov_by_day
    description: "{{ doc('aov_by_day') }}"
    columns:
      - name: order_date
        tests: [not_null, unique]
