name: dbt (DuckDB)

on:
  workflow_dispatch: {}  # enables the blue "Run workflow" button
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dbt (duckdb)
        run: |
          python -m pip install --upgrade pip
          pip install "dbt-duckdb>=1.7.0,<2.0.0"

      - name: dbt deps
        run: dbt deps --profiles-dir .

      - name: dbt seed
        run: dbt seed --profiles-dir .

      - name: dbt run
        run: dbt run --profiles-dir .

      - name: dbt test
        run: dbt test --profiles-dir .

      - name: dbt snapshot
        run: dbt snapshot --profiles-dir .

      - name: dbt docs generate
        run: dbt docs generate --profiles-dir .

      - name: Upload artifacts (target/ + DuckDB file)
        uses: actions/upload-artifact@v4
        with:
          name: dbt-target-and-duckdb
          path: |
            target/
            ecommerce.duckdb

      - name: Upload docs for Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./target

  deploy-docs:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'push' }}
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
